version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9999:9999"
    env_file:
      - .env
    volumes:
      - .:/app
    deploy:
      resources:
        limits:
          cpus: "1"     # Limits to 1 CPU core
          memory: "1GB"  # Limits to 256M of RAM
        reservations:
          cpus: "0.5"     # Optional: Reserves 0.5 CPU cores
          memory: "256M"  # Optional: Reserves 256MB of RAM
    restart: always